[project]
name = "advanced_python"
version = "0.0.1"
description = "Репозиторий с домашками"
requires-python = ">=3.10"
dependencies = [
    "click==8.1.8",
    "colorama==0.4.6",
    "numpy>=2.2.4",
]
